name: MOBACraft
version: v@version@-b@BUILD_NUMBER@
main: com.aethercraft.moba.MOBACraft
author: AEtherSurfer
authors: [AEtherSurfer, fragstel]
softdepend: [Essentials, mcMMO]
commands:
  moba:
    description: Reference command for MOBACraft.
    aliases: [mb]